application: raadioapp
version: 2011-09-08
runtime: python
api_version: 1

inbound_services:
- channel_presence

handlers:
- url: /favicon.ico
  static_files: rrr.png
  upload: rrr.png
  expiration: "90d"

- url: /rrr.png
  static_files: rrr.png
  upload: rrr.png
  expiration: "90d"

- url: /apple-touch-icon.png
  static_files: rrr.png
  upload: rrr.png
  expiration: "90d"

- url: /safari.png
  static_files: safari.png
  upload: safari.png
  expiration: "90d"

- url: .*
  script: main.py
