application: raadioapp
version: 2012-03-16
runtime: python27
api_version: 1
threadsafe: true


libraries:
- name: jinja2
  version: "2.6"


inbound_services:
- channel_presence


handlers:
- url: /favicon.ico
  static_files: images/rrr.png
  upload: images/rrr.png
  expiration: "90d"

- url: /rrr.png
  static_files: images/rrr.png
  upload: images/rrr.png
  expiration: "90d"

- url: /apple-touch-icon.png
  static_files: images/rrr.png
  upload: images/rrr.png
  expiration: "90d"

- url: /update.*
  script: scripts.update.app
  login: admin

- url: .*
  script: scripts.show.app
  login: required
